### ISSUE TITLE
where's the course for this lecture?

### ISSUE THREAD

**Issue by ghost** [spatialaudio/digital-signal-processing-lecture#10]

**Comment by spors** [comment]
The materials are part of my masters course "[Digital Signal Processing](https://lsf.uni-rostock.de/qisserver/rds?state=verpublish&status=init&vmfile=no&publishid=126102&moduleCall=webInfo&publishConfFile=webInfo&publishSubDir=veranstaltung&noDBAction=y&init=y)" at the [University Rostock](https://www.uni-rostock.de/en/), Germany. If you are enrolled at University Rostock you may find information how to enroll in the course in [Stud.IP](https://studip.uni-rostock.de/).
