### ISSUE TITLE
Corrections in correlation_functions

### ISSUE THREAD

**Issue by PrinzessinLea** [spatialaudio/digital-signal-processing-lecture#13]
not quite sure about it: at the end of the paragraph of the properties of the ACF doesn't the variance and the squared linear mean have to be multiplied with the Diraq?

In the second exercise i think the period time is 0,01 s and not 0,1 s.

**Comment by spors** [comment]
> not quite sure about it: at the end of the paragraph of the properties of the ACF doesn't the variance and the squared linear mean have to be multiplied with the Diraq?

I checked the equations. One way of deriving the ACF of an uncorrelated WSS random signal is to express the signal as a superposition of its (deterministic) linear mean and its mean-free component. Re-evaluating the ACF in this case yields the sum of the squared linear mean and the ACF of the mean-free component. 

Hope this helps?
