### ISSUE TITLE
Corrections in white_noise

### ISSUE THREAD

**Issue by PrinzessinLea** [spatialaudio/digital-signal-processing-lecture#15]
in the first code box the second comment should be `#plot PDF`

In the example about Amplifier Noise it would be easier to use simply 
`mean_np = np.mean(noise)
variance_np = np.var(noise)`
or to make a comment that `mean, sigma = stats.norm.fit(noise)` is actually doing only that in case of a normal distribution but can be used for other distributions as well. I spent quite some time to understand what stat.norm.fit does and I am still not very sure about it.

**Comment by PrinzessinLea** [comment]
There is a typo in the solution of the first exercise:
"Solution: The average power of a mean-free random signal is given by **its** variance...."

**Comment by spors** [comment]
Thanks for these comments!
