### ISSUE TITLE
Binder error

### ISSUE THREAD

**Issue by f-brinkmann** [spatialaudio/digital-signal-processing-lecture#7]
Using binder seems to be broken - or do I miss something?

This is the binder error: The legacy buildpack was removed in January 2020. Please see https://repo2docker.readthedocs.io/en/latest/configuration/index.html for alternative ways for configuring your repository

**Comment by spors** [comment]
Thanks for pointing this out! I have removed the `Dockerfile` as this is not required anymore for the binder configuration. Now the build works again.
